### ISSUE TITLE
Ability to parse variable-length fields or arrays

### ISSUE THREAD

**Issue by cyberic99** [alexras/bread#8]
Would it be possible to add support for parsing structs like that:
example_header = [
    ('string_len', b.uint16),
    ('string', b.string(string_len))]
or maybe it is already possible to use a callback?

Thank you

**Comment by alexras** [comment]
It would certainly be possible, and the value of the addition is pretty clear. 

This would effectively mean that updating the values of fields would have to cause re-computation of some or all of the other fields' offsets. Right now, offset calculation is pretty naïve; "parent" structures set their children's offsets based on their offset statically when the struct's parsed. 

Callback-based size calculation seems like a bridge too far; the incidental complexity imposed is pretty high. If you were only allowed to refer to a field that preceded you in the struct definition, that would bound the complexity of the implementation quite a bit. 

If I've got some spare time in the next week or two, I'll take a look at this.

**Comment by cyberic99** [comment]
Okay, thanks for considering adding this feature, it would be a great addition!
Have you seen also my comment on issue #7 ?
Maybe you got no notification, because it was already closed when I added the comment. Thx

**Comment by cyberic99** [comment]
Hello! just wanted to know if there was something new on that matter...
I tried to implement this feature but it is not very 'pythonic', and it recomputes the whole bread struct when a variable len field is encountered...
I also got an issue because arrays can have variable fields inside them so I have to duplicate the child structure n times...
Do you have a solution or a suggestion even if the parsing time is increased?

Thanks

**Comment by alexras** [comment]
It's been a long time since I've looked at the source, but here are some high-level thoughts:

The only things that you'd want to be variable-length are strings and arrays (I think). If you created two new field types - `varstring` and `vararray`, let's say - that treated their first n bytes as a length, it's likely that you could integrate those new field types into the existing set of fields and use the same parsing and generation logic as before.

Unfortunately, I don't have any time to implement new features right now, but I'm happy to provide feedback on any PRs.

Please let me know if you'd like me to clarify any of this.
