### ISSUE TITLE
._field_strings() returns stringified values

### ISSUE THREAD

**Issue by cyberic99** [alexras/bread#9]
In fact, I needed a way to get a list of every child of an object.
If the object contains conditional fields, I get strange values.

Take for instance a lsdj instrument (yes, I know there are functions to do this ;-)):
```
    n0 = b.new(instrument)
    print(n0._field_strings())
```
gives:
```
['instrument_type: pulse', 'envelope: 0\nphase_transpose: 0\nhas_sound_length: False\nsound_length: 0\nsweep: 0\nautomate: False\nautomate_2: False\nvibrato: {\n    type: hf\n    direction: down\n  }\ntable_on: False\ntable: 0\nwave: 12.5%\nphase_finetune: 0\npan: Invalid']
```
This is because of this, in bread.py:
```
            elif isinstance(field, BreadConditional):
                field_strings.append(str(field))
```
Is there a clean way to get a list of children?

Thanks

**Comment by alexras** [comment]
The easiest way to do this is probably

```python
n0.as_native().keys()
```

Generally speaking, `as_native()` will give you a dict, which you can manipulate as you would a normal Python `dict`.

For future reference: unless documented, anything beginning with `_` is not part of the public-facing interface and shouldn't be used, since it can change without notice.
